/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendsResponseV2DevicesInnerProcessorType : Details of the processor type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInnerProcessorType {
    /// The family of the processor
    #[serde(
        rename = "family",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub family: Option<Option<String>>,
    /// The revision of the processor
    #[serde(
        rename = "revision",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub revision: Option<Option<String>>,
    /// The segment of the processor
    #[serde(
        rename = "segment",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub segment: Option<Option<String>>,
}

impl BackendsResponseV2DevicesInnerProcessorType {
    /// Details of the processor type
    pub fn new() -> BackendsResponseV2DevicesInnerProcessorType {
        BackendsResponseV2DevicesInnerProcessorType {
            family: None,
            revision: None,
            segment: None,
        }
    }
}
