/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered : 2Q error (layered)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered {
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

impl BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered {
    /// 2Q error (layered)
    pub fn new(value: f64) -> BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered {
        BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered { value, unit: None }
    }
}
