/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequestOneOf {
    /// The maximum time (in seconds) for the session to run, subject to plan limits.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<u64>,
    /// Execution mode to run the session in
    #[serde(rename = "mode")]
    pub mode: Mode,
    /// Name that identifies the backend on which to set session.
    #[serde(rename = "backend")]
    pub backend: String,
}

impl CreateSessionRequestOneOf {
    pub fn new(mode: Mode, backend: String) -> CreateSessionRequestOneOf {
        CreateSessionRequestOneOf {
            max_ttl: None,
            mode,
            backend,
        }
    }
}
/// Execution mode to run the session in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "dedicated")]
    Dedicated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Dedicated
    }
}
