/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInstance200Response : Instance
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInstance200Response {
    /// Says whether instance is configured to run jobs using Q-Ctrl channel strategy
    #[serde(rename = "qctrl_enabled", skip_serializing_if = "Option::is_none")]
    pub qctrl_enabled: Option<bool>,
}

impl GetInstance200Response {
    /// Instance
    pub fn new() -> GetInstance200Response {
        GetInstance200Response {
            qctrl_enabled: None,
        }
    }
}
