# .github/release.yaml
changelog:
  exclude:
    labels:
      - ignore-for-release
      - documentation
      - infra
    authors:
      - github-actions # exclude GitHub actions bot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Other Changes
      labels:
        - "*" # all other labels
