//
// (C) Copyright IBM 2024
//
// This code is licensed under the Apache License, Version 2.0. You may
// obtain a copy of this license in the LICENSE.txt file in the root directory
// of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
//
// Any modifications or derivative works of this code must retain this
// copyright notice, and modified files need to carry a notice indicating
// that they have been altered from the originals.

//! # direct_access_client
//!
//! This is a Rust client to interact with IBM Quantum backend using the Direct Access API.
//!
//! The Direct Access API provides easy integrations of client’s on-premise IBM Quantum backend
//! and their scheduler/workflow.
//!
//! # Authentication
//! - [`API authentication`](crate::ClientBuilder::with_auth) by
//!   - a short lived access token generated by IBM Cloud Identity and Access Management (IAM) or
//!   - a short lived access token generated by IBM Cloud App ID or
//!   - internal shared key by passing client ID and its shared token
//! # Backend
//! - [`Returns a list of backends enabled for direct access.`](crate::Client::list_backends)
//! - [`Returns details of a backend.`](crate::Client::get_backend)
//! - [`Returns configuration of a backend.`](crate::Client::get_backend_configuration)
//! - [`Returns pulse defaults of a backend.`](crate::Client::get_backend_pulse_defaults)
//! - [`Returns properties of a backend.`](crate::Client::get_backend_properties)
//! # Job
//! - [`Returns jobs submitted by current client in ascending order of created time by default.`](crate::Client::list_jobs)
//! - [`Invoke a Qiskit Runtime primitive.`](crate::Client::run_job)
//! - [`Deletes a job if it has terminated.`](crate::Client::delete_job)
//! - [`Cancels a job if it has not yet terminated.`](crate::Client::cancel_job)
//! # Version
//! - [`Returns the current version of the service`](crate::Client::get_service_version)
//!

mod api;
mod client;
#[allow(dead_code)]
#[allow(unused_imports)]
mod middleware;
pub mod models;
mod storages;
pub mod utils;

pub use client::{AuthMethod, Client, ClientBuilder, PrimitiveJob};
