/*
 * This code is part of Qiskit.
 *
 * (C) Copyright IBM, Pasqal 2026
 *
 * This program and the accompanying materials are made available under the
 * terms of the GNU General Public License version 3, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <[https://www.gnu.org/licenses/gpl-3.0.txt]
 */

#ifndef _SPANK_QRMI_H
#define _SPANK_QRMI_H

#include <unistd.h>
#include <sys/types.h>
#include "buf.h"
#include "qrmi.h"
#include "strbuf.h"

typedef enum {
    KEEP_IF_EXISTS = 0,
    OVERWRITE      = 1,
} setenv_flags_t;

/*
 * max uint32_t value is (2147483647) = 10 chars
 */
#define MAX_INT_STRLEN 10

/*
 * max length of error messages generated by init_post_opt().
 */
#define MAX_ERROR_STRLEN 4096

/*
 * Macro for unused parameters
 *
 * Usage:
 *   UNUSED_PARAM(argv);
 */
#define UNUSED_PARAM(x) (void)(x)

/*
 * Log a debug message when entering a SPANK hook.
 * Emits the plugin name, PID, UID, function name, argument count,
 * and whether the hook is running in the remote (slurmd) context.
 *
 * Usage: place at the top of a spank hook function, before any logic.
 *   SPANK_DEBUG_ENTER(spank_ctxt, argc);
 */
#define SPANK_DEBUG_ENTER(ctxt, argc) \
    slurm_debug("%s(%d, %d): -> %s argc=%d remote=%d", \
                plugin_name, (int)getpid(), (int)getuid(), \
                __func__, (argc), spank_remote(ctxt))

/*
 * Log a debug message when leaving a SPANK hook.
 * Emits the plugin name, PID, UID, and function name.
 *
 * Usage: place just before the final return statement of a spank hook.
 *   SPANK_DEBUG_LEAVE();
 */
#define SPANK_DEBUG_LEAVE() \
    slurm_debug("%s(%d,%d): <- %s", \
                plugin_name, (int)getpid(), (int)getuid(), __func__)

/*
 * A record of acquired QPU resource.
 */
typedef struct _qpu_resource {
    char *name;              /* resource identifier */
    QrmiResourceType type;   /* resource type */
    char *type_as_str;       /* resource type as string */
    char *acquisition_token; /* acquisition token returned by QRMI */
} qpu_resource_t;

/*
 * A record of error occurred in init_post_opt().
 */
typedef struct _qrmi_error {
    char *message;           /* error message */
} qrmi_error_t;

#endif /* !_SPANK_QRMI_H */
