---
version: 1

root:
  level: WARN
  handlers: [console]

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

formatters:
  simple:
    format: '%(asctime)s %(name)-19s %(levelname)-8s %(process)d [%(filename)s:%(lineno)d] %(message)s'

loggers:
  uvicorn:
    handlers:
    - console
    level: INFO
    propagate: false

  api:
    handlers:
    - console
    level: INFO
    propagate: false

  daa_sim.daa_service:
    handlers:
    - console
    level: INFO
    propagate: false
