/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsUsage200Response {
    /// Total usage (in milliseconds)
    #[serde(rename = "usage")]
    pub usage: f64,
    /// Total number of jobs
    #[serde(rename = "jobs")]
    pub jobs: f64,
    /// Total number of sessions
    #[serde(rename = "sessions")]
    pub sessions: f64,
    /// Total sessions usage (in milliseconds)
    #[serde(rename = "sessions_usage")]
    pub sessions_usage: f64,
    /// Average sessions usage (in milliseconds)
    #[serde(rename = "avg_sessions_usage")]
    pub avg_sessions_usage: f64,
    /// Max sessions usage (in milliseconds)
    #[serde(rename = "max_sessions_usage")]
    pub max_sessions_usage: f64,
    /// Total number of batch sessions
    #[serde(rename = "batch_sessions")]
    pub batch_sessions: f64,
    /// Total batch sessions usage (in milliseconds)
    #[serde(rename = "batch_sessions_usage")]
    pub batch_sessions_usage: f64,
    /// Average batch sessions usage (in milliseconds)
    #[serde(rename = "avg_batch_sessions_usage")]
    pub avg_batch_sessions_usage: f64,
    /// Max batch sessions usage (in milliseconds)
    #[serde(rename = "max_batch_sessions_usage")]
    pub max_batch_sessions_usage: f64,
    /// Total number of dedicated sessions
    #[serde(rename = "dedicated_sessions")]
    pub dedicated_sessions: f64,
    /// Total dedicated sessions usage (in milliseconds)
    #[serde(rename = "dedicated_sessions_usage")]
    pub dedicated_sessions_usage: f64,
    /// Average dedicated sessions usage (in milliseconds)
    #[serde(rename = "avg_dedicated_sessions_usage")]
    pub avg_dedicated_sessions_usage: f64,
    /// Max dedicated sessions usage (in milliseconds)
    #[serde(rename = "max_dedicated_sessions_usage")]
    pub max_dedicated_sessions_usage: f64,
    /// Total number of individual jobs
    #[serde(rename = "individual_jobs")]
    pub individual_jobs: f64,
    /// Total individual jobs usage  (in milliseconds)
    #[serde(rename = "individual_jobs_usage")]
    pub individual_jobs_usage: f64,
    /// Average individual jobs usage  (in milliseconds)
    #[serde(rename = "avg_individual_jobs_usage")]
    pub avg_individual_jobs_usage: f64,
    /// Max individual jobs usage (in milliseconds)
    #[serde(rename = "max_individual_jobs_usage")]
    pub max_individual_jobs_usage: f64,
    /// Total queue time (in milliseconds)
    #[serde(rename = "queue_time")]
    pub queue_time: f64,
    /// Average queue time (in milliseconds)
    #[serde(rename = "avg_queue_time")]
    pub avg_queue_time: f64,
    /// Max queue time  (in milliseconds)
    #[serde(rename = "max_queue_time")]
    pub max_queue_time: f64,
}

impl AnalyticsUsage200Response {
    pub fn new(
        usage: f64,
        jobs: f64,
        sessions: f64,
        sessions_usage: f64,
        avg_sessions_usage: f64,
        max_sessions_usage: f64,
        batch_sessions: f64,
        batch_sessions_usage: f64,
        avg_batch_sessions_usage: f64,
        max_batch_sessions_usage: f64,
        dedicated_sessions: f64,
        dedicated_sessions_usage: f64,
        avg_dedicated_sessions_usage: f64,
        max_dedicated_sessions_usage: f64,
        individual_jobs: f64,
        individual_jobs_usage: f64,
        avg_individual_jobs_usage: f64,
        max_individual_jobs_usage: f64,
        queue_time: f64,
        avg_queue_time: f64,
        max_queue_time: f64,
    ) -> AnalyticsUsage200Response {
        AnalyticsUsage200Response {
            usage,
            jobs,
            sessions,
            sessions_usage,
            avg_sessions_usage,
            max_sessions_usage,
            batch_sessions,
            batch_sessions_usage,
            avg_batch_sessions_usage,
            max_batch_sessions_usage,
            dedicated_sessions,
            dedicated_sessions_usage,
            avg_dedicated_sessions_usage,
            max_dedicated_sessions_usage,
            individual_jobs,
            individual_jobs_usage,
            avg_individual_jobs_usage,
            max_individual_jobs_usage,
            queue_time,
            avg_queue_time,
            max_queue_time,
        }
    }
}
