/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsFilters200ResponseBackendsInner {
    #[serde(rename = "name")]
    pub name: String,
}

impl AnalyticsFilters200ResponseBackendsInner {
    pub fn new(name: String) -> AnalyticsFilters200ResponseBackendsInner {
        AnalyticsFilters200ResponseBackendsInner { name }
    }
}
