/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnalyticsFilters200ResponseUsersInner {
    #[serde(rename = "id")]
    pub id: String,
}

impl AnalyticsFilters200ResponseUsersInner {
    pub fn new(id: String) -> AnalyticsFilters200ResponseUsersInner {
        AnalyticsFilters200ResponseUsersInner { id }
    }
}
