/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest : 2Q error (best)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest {
    #[serde(rename = "value")]
    pub value: f64,
    #[serde(rename = "gate")]
    pub gate: String,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(rename = "qubits")]
    pub qubits: Vec<f64>,
}

impl BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest {
    /// 2Q error (best)
    pub fn new(
        value: f64,
        gate: String,
        qubits: Vec<f64>,
    ) -> BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest {
        BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest {
            value,
            gate,
            unit: None,
            qubits,
        }
    }
}
