/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInner {
    /// The name of the backend device
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: Box<models::BackendsResponseV2DevicesInnerStatus>,
    /// Indicates if the device is a simulator
    #[serde(rename = "is_simulator", skip_serializing_if = "Option::is_none")]
    pub is_simulator: Option<bool>,
    /// The number of qubits in the device
    #[serde(
        rename = "qubits",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub qubits: Option<Option<i32>>,
    #[serde(
        rename = "clops",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub clops: Option<Option<Box<models::BackendsResponseV2DevicesInnerClops>>>,
    #[serde(
        rename = "processor_type",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub processor_type: Option<Option<Box<models::BackendsResponseV2DevicesInnerProcessorType>>>,
    /// The number of jobs waiting to be executed
    #[serde(rename = "queue_length")]
    pub queue_length: i32,
    #[serde(
        rename = "performance_metrics",
        skip_serializing_if = "Option::is_none"
    )]
    pub performance_metrics: Option<Box<models::BackendsResponseV2DevicesInnerPerformanceMetrics>>,
}

impl BackendsResponseV2DevicesInner {
    pub fn new(
        name: String,
        status: models::BackendsResponseV2DevicesInnerStatus,
        queue_length: i32,
    ) -> BackendsResponseV2DevicesInner {
        BackendsResponseV2DevicesInner {
            name,
            status: Box::new(status),
            is_simulator: None,
            qubits: None,
            clops: None,
            processor_type: None,
            queue_length,
            performance_metrics: None,
        }
    }
}
