/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInnerPerformanceMetrics {
    #[serde(rename = "two_q_error_best", skip_serializing_if = "Option::is_none")]
    pub two_q_error_best:
        Option<Box<models::BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorBest>>,
    #[serde(
        rename = "two_q_error_layered",
        skip_serializing_if = "Option::is_none"
    )]
    pub two_q_error_layered:
        Option<Box<models::BackendsResponseV2DevicesInnerPerformanceMetricsTwoQErrorLayered>>,
}

impl BackendsResponseV2DevicesInnerPerformanceMetrics {
    pub fn new() -> BackendsResponseV2DevicesInnerPerformanceMetrics {
        BackendsResponseV2DevicesInnerPerformanceMetrics {
            two_q_error_best: None,
            two_q_error_layered: None,
        }
    }
}
