/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BackendsResponseV2DevicesInnerClops : Details of the CLOPS
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BackendsResponseV2DevicesInnerClops {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "value")]
    pub value: i32,
}

impl BackendsResponseV2DevicesInnerClops {
    /// Details of the CLOPS
    pub fn new(r#type: Type, value: i32) -> BackendsResponseV2DevicesInnerClops {
        BackendsResponseV2DevicesInnerClops { r#type, value }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "virtual")]
    Virtual,
    #[serde(rename = "hardware")]
    Hardware,
}

impl Default for Type {
    fn default() -> Type {
        Self::Virtual
    }
}
