/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSessionRequestOneOf1 : Request to create a session. Only for use by channel partner.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequestOneOf1 {
    /// The maximum time (in seconds) between jobs to keep the session active. Must be less than or equal to `active_ttl`.
    #[serde(rename = "interactive_ttl")]
    pub interactive_ttl: u64,
    /// The remaining time (in seconds) for the session to be in the active state while jobs are running. Must be less than or equal to `max_ttl`. Defaults to `max_ttl`.
    #[serde(rename = "active_ttl", skip_serializing_if = "Option::is_none")]
    pub active_ttl: Option<u64>,
    /// The maximum time (in seconds) for the session to run, subject to plan limits.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<u64>,
    /// Execution mode to run the session in
    #[serde(rename = "mode")]
    pub mode: Mode,
}

impl CreateSessionRequestOneOf1 {
    /// Request to create a session. Only for use by channel partner.
    pub fn new(interactive_ttl: u64, mode: Mode) -> CreateSessionRequestOneOf1 {
        CreateSessionRequestOneOf1 {
            interactive_ttl,
            active_ttl: None,
            max_ttl: None,
            mode,
        }
    }
}
/// Execution mode to run the session in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "dedicated")]
    Dedicated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Batch
    }
}
