/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateSessionRequest {
    CreateSessionRequestOneOf(Box<models::CreateSessionRequestOneOf>),
    CreateSessionRequestOneOf1(Box<models::CreateSessionRequestOneOf1>),
}

impl Default for CreateSessionRequest {
    fn default() -> Self {
        Self::CreateSessionRequestOneOf(Default::default())
    }
}
/// Execution mode to run the session in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "dedicated")]
    Dedicated,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Batch
    }
}
