/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateJobRequest {
    CreateJobRequestOneOf(Box<models::CreateJobRequestOneOf>),
    CreateJobRequestOneOf1(Box<models::CreateJobRequestOneOf1>),
}

impl Default for CreateJobRequest {
    fn default() -> Self {
        Self::CreateJobRequestOneOf(Default::default())
    }
}
/// Logging level of the program
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "critical")]
    Critical,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "debug")]
    Debug,
}

impl Default for LogLevel {
    fn default() -> LogLevel {
        Self::Critical
    }
}
