/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateJob200Response : Response when creating a job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateJob200Response {
    /// Job ID
    #[serde(rename = "id")]
    pub id: String,
    /// Backend selected to run job
    #[serde(rename = "backend")]
    pub backend: String,
    /// Id of the session associated with the job
    #[serde(rename = "session_id", skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

impl CreateJob200Response {
    /// Response when creating a job
    pub fn new(id: String, backend: String) -> CreateJob200Response {
        CreateJob200Response {
            id,
            backend,
            session_id: None,
        }
    }
}
