/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateSession200ResponseTimestampsInner : Contains information about the time a specific status transition happened
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSession200ResponseTimestampsInner {
    /// The state of the session. - open: The session is waiting to run jobs. - active: The session has priority to run jobs on the backend and is running jobs or is waiting for more jobs to run. - inactive: The session does not have priority and is not running any jobs. - closed: The session is not running any jobs and will not accept/run new jobs.
    #[serde(rename = "status")]
    pub status: Status,
    /// Timestamp of when the session transitioned into the given status
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl CreateSession200ResponseTimestampsInner {
    /// Contains information about the time a specific status transition happened
    pub fn new(status: Status, timestamp: String) -> CreateSession200ResponseTimestampsInner {
        CreateSession200ResponseTimestampsInner { status, timestamp }
    }
}
/// The state of the session. - open: The session is waiting to run jobs. - active: The session has priority to run jobs on the backend and is running jobs or is waiting for more jobs to run. - inactive: The session does not have priority and is not running any jobs. - closed: The session is not running any jobs and will not accept/run new jobs.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "closed")]
    Closed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Open
    }
}
