/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FindInstanceWorkloads401Response {
    #[serde(rename = "errors")]
    pub errors: Vec<models::FindInstanceWorkloads401ResponseErrorsInner>,
}

impl FindInstanceWorkloads401Response {
    pub fn new(
        errors: Vec<models::FindInstanceWorkloads401ResponseErrorsInner>,
    ) -> FindInstanceWorkloads401Response {
        FindInstanceWorkloads401Response { errors }
    }
}
