/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAccountConfig200Response : Configuration for an account managed by the IBM Qiskit Runtime service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountConfig200Response {
    /// The list of configurations for the account per plan
    #[serde(rename = "plans")]
    pub plans: Vec<models::GetAccountConfig200ResponsePlansInner>,
}

impl GetAccountConfig200Response {
    /// Configuration for an account managed by the IBM Qiskit Runtime service.
    pub fn new(
        plans: Vec<models::GetAccountConfig200ResponsePlansInner>,
    ) -> GetAccountConfig200Response {
        GetAccountConfig200Response { plans }
    }
}
