/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetInstanceConfiguration200Response : Instance configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInstanceConfiguration200Response {
    /// Instance usage limit in seconds
    #[serde(rename = "instance_limit", skip_serializing_if = "Option::is_none")]
    pub instance_limit: Option<f64>,
}

impl GetInstanceConfiguration200Response {
    /// Instance configuration
    pub fn new() -> GetInstanceConfiguration200Response {
        GetInstanceConfiguration200Response {
            instance_limit: None,
        }
    }
}
