/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUsageAnalyticsGroupedByDate200Response {
    /// Interval start
    #[serde(rename = "interval_start")]
    pub interval_start: String,
    /// Interval end
    #[serde(rename = "interval_end")]
    pub interval_end: String,
    /// Results
    #[serde(rename = "data")]
    pub data: Vec<models::GetUsageAnalyticsGroupedByDate200ResponseDataInner>,
}

impl GetUsageAnalyticsGroupedByDate200Response {
    pub fn new(
        interval_start: String,
        interval_end: String,
        data: Vec<models::GetUsageAnalyticsGroupedByDate200ResponseDataInner>,
    ) -> GetUsageAnalyticsGroupedByDate200Response {
        GetUsageAnalyticsGroupedByDate200Response {
            interval_start,
            interval_end,
            data,
        }
    }
}
