/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountConfig200ResponsePlansInner {
    /// The plan id as defined in Global Catalog
    #[serde(rename = "plan_id")]
    pub plan_id: String,
    /// The maximum sum of allowable usage allocation across all instances in the account.
    #[serde(rename = "usage_allocation_seconds")]
    pub usage_allocation_seconds: i32,
    /// List of backends to allow the account to assign for instances.
    #[serde(rename = "backends")]
    pub backends: Vec<String>,
    /// The maximum time (in seconds) for session to run, subject to plan limits.
    #[serde(rename = "max_ttl", skip_serializing_if = "Option::is_none")]
    pub max_ttl: Option<i32>,
    /// The remaining time (in seconds) for the session to be in the active state while jobs are running. Must be less than or equal to max ttl.
    #[serde(rename = "active_ttl", skip_serializing_if = "Option::is_none")]
    pub active_ttl: Option<i32>,
    /// The maximum time (in seconds) between jobs to keep the session active. Must be less than or equal to active ttl.
    #[serde(rename = "interactive_ttl", skip_serializing_if = "Option::is_none")]
    pub interactive_ttl: Option<i32>,
    /// The remaining usage allocation that can still be allocated to instances.
    #[serde(
        rename = "unallocated_usage_seconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub unallocated_usage_seconds: Option<i32>,
}

impl GetAccountConfig200ResponsePlansInner {
    pub fn new(
        plan_id: String,
        usage_allocation_seconds: i32,
        backends: Vec<String>,
    ) -> GetAccountConfig200ResponsePlansInner {
        GetAccountConfig200ResponsePlansInner {
            plan_id,
            usage_allocation_seconds,
            backends,
            max_ttl: None,
            active_ttl: None,
            interactive_ttl: None,
            unallocated_usage_seconds: None,
        }
    }
}
