/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobMetricsTimestamps : A map of status transitions to timestamps
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobMetricsTimestamps {
    /// Timestamp of when the job create request was received
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// Timestamp of when the job finished
    #[serde(rename = "finished", skip_serializing_if = "Option::is_none")]
    pub finished: Option<String>,
    /// Timestamp of when the job started running
    #[serde(rename = "running", skip_serializing_if = "Option::is_none")]
    pub running: Option<String>,
}

impl JobMetricsTimestamps {
    /// A map of status transitions to timestamps
    pub fn new() -> JobMetricsTimestamps {
        JobMetricsTimestamps {
            created: None,
            finished: None,
            running: None,
        }
    }
}
