/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListBackends200Response {
    BackendsResponseV2(Box<models::BackendsResponseV2>),
}

impl Default for ListBackends200Response {
    fn default() -> Self {
        Self::BackendsResponseV2(Default::default())
    }
}
