/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListJobs400ResponseErrorsInner {
    /// Error type identifier
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Explanation of the problem
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// URL where information about the error can be read in a web browser
    #[serde(rename = "more_info", skip_serializing_if = "Option::is_none")]
    pub more_info: Option<String>,
}

impl ListJobs400ResponseErrorsInner {
    pub fn new() -> ListJobs400ResponseErrorsInner {
        ListJobs400ResponseErrorsInner {
            code: None,
            message: None,
            more_info: None,
        }
    }
}
