/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListJobs400Response : Error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListJobs400Response {
    /// A request identifier
    #[serde(rename = "trace", skip_serializing_if = "Option::is_none")]
    pub trace: Option<String>,
    /// A list of errors
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::ListJobs400ResponseErrorsInner>>,
}

impl ListJobs400Response {
    /// Error response
    pub fn new() -> ListJobs400Response {
        ListJobs400Response {
            trace: None,
            errors: None,
        }
    }
}
