/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReplaceJobTagsRequest : Replace job tags request
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReplaceJobTagsRequest {
    /// List of job or program tags
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
}

impl ReplaceJobTagsRequest {
    /// Replace job tags request
    pub fn new(tags: Vec<String>) -> ReplaceJobTagsRequest {
        ReplaceJobTagsRequest { tags }
    }
}
