/*
 * Qiskit Runtime API
 *
 * The Qiskit Runtime API description
 *
 * The version of the OpenAPI document: 0.21.2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSessionStateRequest {
    /// If true, the session is actively accepting new jobs to be queued. If false, jobs will be rejected on create and the session will be immediately closed when there are no more jobs to run in the session.
    #[serde(rename = "accepting_jobs")]
    pub accepting_jobs: bool,
}

impl UpdateSessionStateRequest {
    pub fn new(accepting_jobs: bool) -> UpdateSessionStateRequest {
        UpdateSessionStateRequest { accepting_jobs }
    }
}
