[package]
name = "utility"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Qiskit/direct-access-client"
license = "Apache-2.0"

[dependencies]
direct-access-api = { workspace = true }
tokio = { version = "1.40.0", features = ["full"] }
env_logger = "0.11.5"
