name: Doxygen Documentation Workflow

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  schedule:
    - cron: '0 12 * * 1'  # Runs every Monday at 12:00 UTC (weekly schedule)
jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Install Doxygen and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate documentation
        run: |
          doxygen Doxyfile

      - name: Upload documentation artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: C_Documentation
          path: ./docs/html

      - name: Display documentation summary (optional)
        run: |
          echo "Documentation generated and stored as artifacts."