name: Build & Test
on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    # TODO: For the action to work, we need to supply a mysql
    # service as defined below.
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "8888:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:

      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup Test SLURM Cluster
        uses: koesterlab/setup-slurm-action@v1
        # Afterwards, We can submit to the slurm cluster via sbatch and srun,
        # and interact via all other usual commands.
